spring:
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/app_2022_10_05_test?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root123
  jpa:
    hibernate:
      ddl-auto: create